apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-configmap
data:
  local-config.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        address: 0.0.0.0
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 15m       # Any chunk not receiving new logs in this time will be flushed
      max_chunk_age: 1h            # All chunks will be flushed when they hit this age, oldest first
      chunk_target_size: 1048576   # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first

    schema_config:
      minio:
        bucket_name: "anandbucket1"
        endpoint: "http://192.168.49.2:9000"
        access_key: "15fb4c4195579612fb5259f95f9195be"
        secret_key: "8f4fe1bf54c3efe2e7938e5c6c73c43ee36be38090679e13b627c2fcd58b3eb4"
