# minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31002   # You can choose any available port number
  selector:
    app: minio

