apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
        - -config.file=/etc/promtail/config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/promtail
          readOnly: true
        - name: logs-volume
          mountPath: /var/log/nginx
      volumes:
      - name: config-volume
        configMap:
          name: promtail-config
      - name: logs-volume
        hostPath:
          path: /var/log/nginx

